language: python
notifications:
  email: false
python:
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - pip install -qq flake8 coverage coveralls
  - flake8 superintendent
  - pip install -qq -e '.[tests,examples]'
  # run the test suite
  - coverage run --source=superintendent -m pytest
  - coveralls
  # test that all documentation notebooks can still be run:
  - find docs -name '*.ipynb' -o -name 'examples/*.ipynb' | xargs jupyter nbconvert --to notebook --execute
  # test that all arguments have been documented
  - docargs superintendent --ignore-ambiguous-signatures
