language: python
notifications:
  email: false
python:
  - "3.5"
  - "3.6"
script:
  - pip install -qq flake8 coverage coveralls
  - flake8 superintendent
  - pip install -qq -e '.[tests,examples]'
  - coverage run --source=superintendent -m pytest
  - coveralls
  - docargs superintendent --ignore-ambiguous-signatures
